'use client';
// import type { Metadata } from "next";
import { Oswald, Urbanist } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { useEffect } from "react";
import { useCustomerAuth } from "@/stores/useCustomerAuth";

const urbanist = Urbanist({ subsets: ["latin"] });

const oswald = Oswald({ subsets: ["latin"], variable: "--font-oswald" });

// export const metadata: Metadata = {
//   title: "Nike Store Clone",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    useCustomerAuth.getState().init();
  }, []);
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} ${oswald.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}
